name: Java CI

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:

    name: Build using ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: List files in working dir
      run: ls -alhR ./
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: cd 2022 && ./gradlew build